function F_triref_asymmetry_score_scatter(F_compare_snv_192_output_structure,...
                                          varargin)
%% F_triref_asymmetry_score_scatter
%          F_triref_asymmetry_score_scatter(F_compare_snv_192_output_structure,...
%                                           varargin)
%  NOTE: dependend on the F_compare_snv_192 results, and the mutation type
%        order should be as below:
%        default_snv_asymmetry = {'AT','TA','AG','TC','TG','AC','CT','GA','GT','CA','CG','GC'};
%        default_context_order = {'A','G','T','C'}; 
%  F_triref_asymmetry_score_scatter is to plot the asymmetry scores which 
%  is generated by the F_compare_snv_192 function. 
%  Overall, this function use [asymmetry_score](AS) as input, and then considers  
%  the 3' or 5' adjacent base to scatter the AS. Purine(A or G)-AS is on
%  the X-axis and pyrimidine(T or C)-AS is on the Y-axis, meaning the scattered 
%  [x y] values represent [AS-A AS-T] and/or [AS-G AS-C].
%  Input:
%       F_compare_snv_192_output_structure: The out put structure of the F_compare_snv_192 function.
%  varargin:
%       'scatter':            Plot the scatter considering the 3'- or 5'-adjacent base.
%                             Default    : 'no'
%                             Alternative: 'yes'
%       'paired_comparison' : Plot the paired-sample scatter considering the 3'- or 5'-adjacent base.
%                             Default    : 'yes'
%                             Alternative: 'no'
%       'ylimit'            : Set ylimit to the asymmetry score plots. X
%                             and Y limits are the same.
%       'plot_gene_cluster' : Row indicis to set gene cluster which will be 
%                             used for doing the plots. 
%                             Default    : [2:6], which is to refer the
%                                          gene clusters in the TS paper.
%                             Alternative: row indicis.
%       'sample_name'       : Set sample name to show it in the title of plots.
%
%  Bo Xia 06/12/2019
%% Parse defaul settings and setup inputs
fprintf('****************************************\n')
time1 = datetime;
fprintf('%s   Started scattering the asymmetry scores.\n',datestr(time1))

%default asymmetry calculations: 
%                       A>T/T>A;A>G/T>C;T>G/A>C;C>T/G>A;G>T/C>A;C>G/G>C;
default_snv_asymmetry = {'AT','TA','AG','TC','TG','AC','CT','GA','GT','CA','CG','GC'}; %Don't change!
default_context_order = {'A','G','T','C'}; %Don't change!
default_ylimit      = [-0.35 1]; 
default_plot_gene_cluster      = [2:6]; 
default_scatter = 'no';
default_paired_comparison = 'yes';
default_samplename = '';
ValidYesOrNo = {'no','yes'};
checkYesOrNo = @(x) any(validatestring(x,ValidYesOrNo));

p = inputParser;
addOptional(p,'snv_asymmetry_order',default_snv_asymmetry)
addOptional(p,'sequence_context_order',default_context_order)
addOptional(p,'scatter',default_scatter,checkYesOrNo)
addOptional(p,'paired_comparison',default_paired_comparison,checkYesOrNo)
addOptional(p,'plot_gene_cluster',default_plot_gene_cluster)
addOptional(p,'ylimit',default_ylimit)
addOptional(p,'sample_name',default_samplename)
parse(p,varargin{:})

%default numbers
default_snv_asymmetry = p.Results.snv_asymmetry_order;
default_context_order = p.Results.sequence_context_order;
default_scatter = p.Results.scatter;
default_paired_comparison = p.Results.paired_comparison;
default_plot_gene_cluster = p.Results.plot_gene_cluster;
default_ylimit = p.Results.ylimit;
default_samplename = p.Results.sample_name;

%setup input files
    input = F_compare_snv_192_output_structure;

    %other default values
    AS2             = input.asymmetry_score;          %input asymmetry scores
    rows            = default_plot_gene_cluster;
%     AS              = log2((sum(input.coding_mut_level(2:6,:))./sum(input.coding_ref_freq(2:6,:))) ./ ...
%                            (sum(input.template_mut_level(2:6,:))./sum(input.template_ref_freq(2:6,:)))); 
    muttype         = input.mutation_type;      %mutation type annotation
    backcolor = [229 245 249;254 235 232;230 230 230;239 237 245;229 245 224;254 232 200]/256;
    
%% 3'-base plots
%scatter X-Y plot
if strcmp('yes',cellstr(default_scatter))
    figure;
    line(default_ylimit,default_ylimit);hold on;
    for a = 1:6
        data = []; data2 = [];   
        data = AS2(rows,a*16-15 : a*16);
        data2(:,1) = reshape(data(1:length(rows),1:8)',[8*length(rows),1]);
        data2(:,2) = reshape(data(1:length(rows),9:16)',[8*length(rows),1]);
        type(a) = muttype(3, a*16);
        scatter(data2(:,1),data2(:,2),'filled');hold on;
    end
    axis equal
    xlim(default_ylimit); ylim(default_ylimit);
    ax = gca;
    ax.XAxisLocation = 'origin';
    ax.YAxisLocation = 'origin';
    box off; set(ax,'Color','none');
    title(['(' default_samplename ')' '3-adjacent base: purine(X)-pyrimidine(Y)']);
end

%plot paired_comparison plots and do paired_sample t-test with
%Bonferroni-multiple test correction.
if strcmp('yes',cellstr(default_paired_comparison))
    figure;
    for a = 1:6
        %set up input data
        data = []; data2 = [];        
        data = AS2(rows,a*16-15 : a*16);
        len = length(data(:,1));
        data2(:,1) = reshape(data(:,1:4)',[4*len,1]);    %3'-A
        data2(:,2) = reshape(data(:,5:8)',[4*len,1]);    %3'-G
        data2(:,3) = reshape(data(:,9:12)',[4*len,1]);   %3'-T
        data2(:,4) = reshape(data(:,13:16)',[4*len,1]);  %3'-C
        len2 = length(data2(:,1));
        type(a) = muttype(3, a*16);
        %plot backgound
        area([a-.5 a+.5],[default_ylimit(2) default_ylimit(2)],...
            'FaceColor',backcolor(a,:),'LineStyle','none'); hold on;
        area([a-.5 a+.5],[default_ylimit(1) default_ylimit(1)],...
            'FaceColor',backcolor(a,:),'LineStyle','none'); hold on;
        line([a+0.5 a+0.5],[default_ylimit(1) default_ylimit(2)],'Color',[0.4 0.4 0.4]);
        hold on;
        %plot lines
        plot([repmat(a-0.25,len2*2,1) repmat(a+0.25,len2*2,1)]',...
             [[data2(:,1);data2(:,2)] [data2(:,3);data2(:,4)]]','Color',[0.8 0.8 0.8]); hold on;
        %plot scatters
        s=scatter(repmat(a-0.25,len2,1),data2(:,1),10,...
                'MarkerEdgeColor',[0.1 0.1 0.1],'MarkerFaceColor',[0.7695 0.1055 0.4883]);hold on; %A
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5;
        s=scatter(repmat(a-0.25,len2,1),data2(:,2),10,...
                'MarkerEdgeColor',[.1 .1 .1],'MarkerFaceColor',[0.4961 0.7344 0.2539]);hold on; %G
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5;
        s=scatter(repmat(a+0.25,len2,1),data2(:,3),10,...
                'MarkerEdgeColor',[.1 .1 .1],'MarkerFaceColor',[0.7695 0.1055 0.4883]);hold on; %T
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5; 
        s=scatter(repmat(a+0.25,len2,1),data2(:,4),10,...
                'MarkerEdgeColor',[.1 .1 .1],'MarkerFaceColor',[0.4961 0.7344 0.2539]);hold on; %C
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5; 
        [h(a),pvalue(a)] = ttest([data2(:,1);data2(:,2)], [data2(:,3);data2(:,4)],0.05/6) ; %With Bonferoni multiple-test correction.
        pvalue(a)=pvalue(a)*6; %With Bonferoni multiple-test correction.
        %write p-values
        line([a-0.25 a+0.25],[default_ylimit(2)*0.95 default_ylimit(2)*0.95],'Color',[0 0 0]); hold on;
        text(a-0.5,default_ylimit(2)*0.99,num2cell(pvalue(a)),'FontSize',9); hold on;
        text(a-0.5,default_ylimit(1),type(a),'FontSize',9); hold on;
    end
    %plot legend of dots
    s=scatter(6.3,default_ylimit(2)*0.9,20,...
                'MarkerEdgeColor',[.1 .1 .1],'MarkerFaceColor',[0.4961 0.7344 0.2539]);hold on; %C
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5; 
    text(6.5,default_ylimit(2)*0.9,'G-C pair','FontSize',9); hold on;
    s=scatter(6.3,default_ylimit(2)*0.8,20,...
                'MarkerEdgeColor',[.1 .1 .1],'MarkerFaceColor',[0.7695 0.1055 0.4883]);hold on; %T
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5; 
    text(6.5,default_ylimit(2)*0.8,'A-T pair','FontSize',9); hold off;

    xlim([0.5 6.5]); xticks([0.5 1.5 2.5 3.5 4.5 5.5 6.5]); xticklabels([]);
    ylim(default_ylimit); 
    ax = gca;
    ax.XAxisLocation = 'origin';
    ax.YAxisLocation = 'origin';
    box off; set(ax,'Color','none');
    ylabel('Asymmetry scores');
    title(['(' default_samplename ')' '3-adjacent base: purine(left)-pyrimidine(right)']);
end
%% 5'-base plot
%5' scattering
if strcmp('yes',cellstr(default_scatter))
    figure;
    line(default_ylimit,default_ylimit);hold on;
    for a = 1:6
        data = []; data2 = [];   
        data = AS2(rows,a*16-15 : a*16);
        data2(:,1:2) = [data(1:length(rows),[1 3]);data(1:length(rows),[2 4]);...
                        data(1:length(rows),[5 7]);data(1:length(rows),[6 8]);...
                        data(1:length(rows),[9 11]);data(1:length(rows),[10 12]);...
                        data(1:length(rows),[13 15]);data(1:length(rows),[14 16])];
        type(a) = muttype(3, a*16);
        scatter(data2(:,1),data2(:,2),'filled');hold on;
    end
    axis equal
    xlim(default_ylimit); ylim(default_ylimit);
    ax = gca;
    ax.XAxisLocation = 'origin';
    ax.YAxisLocation = 'origin';
    box off; set(ax,'Color','none');
    title(['(' default_samplename ')' '5-adjacent base: purine(X)-pyrimidine(Y)']);

end

%plot paired_comparison plots and do paired_sample t-test with
%Bonferroni-multiple test correction.
if strcmp('yes',cellstr(default_paired_comparison))
    figure;
    for a = 1:6
        %setup inputs
        data = []; data2 = [];        
        data = AS2(rows,a*16-15 : a*16);
        len = length(data(:,1));
        data2(:,1) = [data(:,1);data(:,5);data(:,9);data(:,13)];    %5'-A
        data2(:,2) = [data(:,2);data(:,6);data(:,10);data(:,14)];    %5'-G
        data2(:,3) = [data(:,3);data(:,7);data(:,11);data(:,15)];   %5'-T
        data2(:,4) = [data(:,4);data(:,8);data(:,12);data(:,16)];  %5'-C
        len2 = length(data2(:,1));
        type(a) = muttype(3, a*16);
        %plot backgound
        area([a-.5 a+.5],[default_ylimit(2) default_ylimit(2)],...
            'FaceColor',backcolor(a,:),'LineStyle','none'); hold on;
        area([a-.5 a+.5],[default_ylimit(1) default_ylimit(1)],...
            'FaceColor',backcolor(a,:),'LineStyle','none'); hold on;
        line([a+0.5 a+0.5],[default_ylimit(1) default_ylimit(2)],'Color',[0.4 0.4 0.4]);
        hold on;
        %plot lines
        plot([repmat(a-0.25,len2*2,1) repmat(a+0.25,len2*2,1)]',...
             [[data2(:,1);data2(:,2)] [data2(:,3);data2(:,4)]]','Color',[0.8 0.8 0.8]); hold on;
        %plot scatters
        s=scatter(repmat(a-0.25,len2,1),data2(:,1),10,...
                'MarkerEdgeColor',[0.1 0.1 0.1],'MarkerFaceColor',[0.7695 0.1055 0.4883]);hold on; %A
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5;
        s=scatter(repmat(a-0.25,len2,1),data2(:,2),10,...
                'MarkerEdgeColor',[.1 .1 .1],'MarkerFaceColor',[0.4961 0.7344 0.2539]);hold on; %G
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5;
        s=scatter(repmat(a+0.25,len2,1),data2(:,3),10,...
                'MarkerEdgeColor',[.1 .1 .1],'MarkerFaceColor',[0.7695 0.1055 0.4883]);hold on; %T
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5; 
        s=scatter(repmat(a+0.25,len2,1),data2(:,4),10,...
                'MarkerEdgeColor',[.1 .1 .1],'MarkerFaceColor',[0.4961 0.7344 0.2539]);hold on; %C
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5; 
        [h(a),pvalue(a)] = ttest([data2(:,1);data2(:,2)], [data2(:,3);data2(:,4)],0.05/6) ; %With Bonferoni multiple-test correction.
        pvalue(a)=pvalue(a)*6; %With Bonferoni multiple-test correction.
        %write p-values
        line([a-0.25 a+0.25],[default_ylimit(2)*0.95 default_ylimit(2)*0.95],'Color',[0 0 0]); hold on;
        text(a-0.5,default_ylimit(2)*0.99,num2cell(pvalue(a)),'FontSize',9); hold on;
        text(a-0.5,default_ylimit(1),type(a),'FontSize',9); hold on;
    end
    %plot legend of dots
    s=scatter(6.3,default_ylimit(2)*0.9,20,...
                'MarkerEdgeColor',[.1 .1 .1],'MarkerFaceColor',[0.4961 0.7344 0.2539]);hold on; %C
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5; 
    text(6.5,default_ylimit(2)*0.9,'G-C pair','FontSize',9); hold on;
    s=scatter(6.3,default_ylimit(2)*0.8,20,...
                'MarkerEdgeColor',[.1 .1 .1],'MarkerFaceColor',[0.7695 0.1055 0.4883]);hold on; %T
            s.MarkerEdgeAlpha=0.2; s.MarkerFaceAlpha=0.5; 
    text(6.5,default_ylimit(2)*0.8,'A-T pair','FontSize',9); hold off;

    xlim([0.5 6.5]); xticks([0.5 1.5 2.5 3.5 4.5 5.5 6.5]); xticklabels([]);
    ylim(default_ylimit); 
    ax = gca;
    ax.XAxisLocation = 'origin';
    ax.YAxisLocation = 'origin';
    box off; set(ax,'Color','none');
    ylabel('Asymmetry scores');
    title(['(' default_samplename ')' '5-adjacent base: purine(left)-pyrimidine(right)']);
end